############# CONFIGS ################

browser = chrome
username = Admin
password = admin123

########################### URLS #################################

URL = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
homepage.URL = https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index
adminpage.jobtitles = https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewJobTitleList
jobtitles.add.url = https://opensource-demo.orangehrmlive.com/web/index.php/admin/saveJobTitle

###################### PATHS #########################

screenshots.path = /screenshots/


################# TITLES ############################

login.title=OrangeHRM
homepage.heading = dashboard


###############  JOB DETAILS  #######################

jobtitle = Automation\ Tester
jobdescription= Design\ and\ implement\ automated\ testing\ scripts\ using\ Selenium\ WebDriver\ to\ ensure\ high\ software\ quality.
note=Remote\ work\ options\ are\ available\ for\ high-performing\ individuals\ who\ demonstrate\ consistent\ delivery.
jobspecificationpathdetails= src/main/resources/RequirementsOfProjects.png
################## Variable Names #############################

# yet to add ooooooooo
